### ISSUE TITLE
redoing config structure mods and features

### ISSUE THREAD

**Issue by NikkyAI** [NikkyAI/alpacka#16]
edit: 
final strusture we go for is 
```yaml
files:
  common:
    - foo

  server:
    side: server
    list:
      - foo

  client:
    side: client
    list:
      - foo
    optional:
      feature: optional
      version: latest
      list:
        - foo
```
with the options of using `&` to link the keys

splitting the mods list in multiple client / server lists
with different sets of default values could allow for a much lighter and easier readable config file

```yaml
mods:											# Dictionary<string, ModList>
  list_Name: 									# ModList
    defaults: 									# ModEntry
      value: default
      othervalue: blub
    list: 										# List<ModEntry>
      - mod name
      - src: http://example.com/file.jar
        version: x.y.z
  other_list:
  ...
```
the comments specify the type of the compound object

the type of mods would change from a list into a dictionary of lists with defaults, which would probably be another custom type
it can all be compacted into a single list for emitting json

examples of the new forma and a comparison to the old onet:
https://gist.github.com/NikkyAI/d7a0fd44e101c85220d4fab715cdb0e4
the old format as far fewer simple lists of strings and lots of repetition, the proposed format looks cleaner, sliwghtly mpre compact and saves ~30 lines in this example

**Comment by copygirl** [comment]
Should it be possible to nest these?

```yaml
mods:

  common:
    - foo

  server:
    defaults: side: server
    list:
      - foo

  client:
    defaults: side: client
    list:
      - foo
    optional:
      defaults:
        feature: optional
        version: latest
      list:
        - foo
```
What about providing common default list names, or defining them beforehand?
```yaml
defaults:
  version: latest
  common:
    version: recommended

mods:
  common:
    - foo
    - bar
  client: ...
  server: ...
  client & optional: ...
  server & optional & latest: ...
```
