### ISSUE TITLE
Discussion: file and folder structure

### ISSUE THREAD

**Issue by NikkyAI** [NikkyAI/alpacka#27]
At the moment we use the `minecraft` folder with all fiels inside

i feel it would by more usful to adapt MultiMC's structure
and keep alpacka related files outside of the minecraft folder
i think it will help with implementing features later because we do not have
`feature/feature_name/somefiles` in the minecraft folder where some mod or minecraft itself might mess with it
the gitignore rules will be more compley because we have to ignore the `patches/` folder and `instance.cfg`.. although the latter could be kept in source control if one so desires (not recommended)

**Comment by copygirl** [comment]
Independent of whether we have a minecraft folder where we store things - which I still need to be convinced of why that's the better choice - here my not entirely thoroughly thought through (hah) idea for how to structure the config specifically, which might also have an effect on the file structure. (I guess this fits more into #16 but whatever.)

```yaml
# ...
mcVersion: 1.11.2
forgeVersion: ...

defaults:
  *: recommended
  # The following might be implemented by default but I'll use them as example.
  client: side: client
  server: side: server
  optional: ... # Have to propose how features work / are defined still.
  recommended: ...
  mods: folder: "mods"
  config: folder: "config"

files:
  
  mods:
    client:
      - Some Client Mod
    server:
      files:
        - Some Server Mod
      optional:
        - Some Server Utility Mod
  
  Some Feature:
    optional: true
    mods:
      - Scripting Mod
      - Feature Mod
    config:
      - foobar.cfg
    scripts:
      folder: scripts
      files:
        - fooscript.scr
        - barscript.scr
```
