### ISSUE TITLE
name, description and links for mods are ignored

### ISSUE THREAD

**Issue by NikkyAI** [NikkyAI/alpacka#33]
currently overriding name, description and links
so any field from https://github.com/NikkyAI/alpacka/blob/master/src/Alpacka.Lib/Pack/EntryMod.cs
is ignored and does not appear in the `packbuild.json`

example:
```yaml
- src: https://asie.pl/files/minecraft/foamfix-0.6.2-beta1-anarchy.jar
  description: cool stuff
  name: fomafix
  links:
    website: https://asie.pl/Projects/Minecraft/Mods/FoamFix/
```

results in 

```json
{
  "src": "https://asie.pl/files/minecraft/foamfix-0.6.2-beta1-anarchy.jar",
  "version": "recommended",
  "path": "mods/foamfix-0.6.2-beta1-anarchy.jar"
},
```
